name: instrbility
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - htslib=1.22.1=h566b1c6_0
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - joblib=1.5.2=py310h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=h46f56fc_0
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.5=py310hc213724_2
  - numpy-base=2.2.5=py310hf387b04_2
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.2=pyh8b19718_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysam=0.23.3=py310h64e62c9_1
  - pytest=8.4.2=pyhcf101f3_1
  - python=3.10.19=h3c07f61_2_cpython
  - python_abi=3.10=8_cp310
  - readline=8.2=h8c095d6_2
  - samtools=1.22.1=h96c455f_0
  - scikit-learn=1.7.2=py310h505adc9_0
  - scipy=1.15.3=py310ha592af2_1
  - setuptools=80.9.0=pyhff2d567_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.3.0=pyhcf101f3_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
prefix: 
  /uufs/chpc.utah.edu/common/HIPAA/u1264408/software/pkg/miniforge3/envs/instrbility
